# POST http://localhost:3000/signup 
# Content-Type: application/json

# {
#     "email": "kunaa@gmail.com",
#     "password": "Kunaal"
# }

POST http://localhost:3000/signin
Content-Type: application/json

# {
#     "fullname": "khai",
#     "email":"khai04@hotmail.com",
#     "password": "Hongkhai02"
# }
{
    "email":"khai04w@hotmail.com",
    "password": "Hongkhai021"
}